from flask import Blueprint, request, jsonify, Response
from core.classify_service import predict_news, prepare_model, ModelUnavailable
from utils.article_extractor import extract_news_data, extract_news_data_safe
from utils.db_utils import (
    get_or_create_source, save_news, get_active_model, save_classification,
    save_consultation, classify_topic, extract_keywords, save_news_keywords,
    save_complete_analysis, get_cached_analysis
)
import logging
from datetime import datetime
import csv
import io
import os
import hmac
import time
import math
from api.internal_auth import require_gateway

# Configuración básica de logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Crear el Blueprint
classify_bp = Blueprint("classify_bp", __name__)

@classify_bp.before_request
def authorize_classification():
    return require_gateway(admin=request.endpoint != 'classify_bp.classify')

def analysis_response(saved):
    return {
        "Consulta ID": saved["consulta_id"], "Noticia ID": saved["noticia_id"],
        "Clasificación ID": saved["clasificacion_id"], "Modelo ID": saved["modelo_id"],
        "Fuente": saved["url"] or "Texto ingresado directamente",
        "Título": saved["titulo"], "Texto Completo": saved["contenido"],
        "Autor": "No disponible" if saved["url"] else "Usuario",
        "Fecha de Publicación": saved["fecha_publicacion"],
        "Clasificación": saved["resultado"], "Confianza": saved["confianza"],
        "Explicación": saved["explicacion"], "Tema": saved["tema"],
        "Palabras Clave": saved["keywords"], "Reutilizado": saved["reutilizado"],
    }


@classify_bp.route("/predict", methods=["POST"])
def classify():
    expected = os.environ.get("ML_GATEWAY_SECRET", "")
    if len(expected) < 32:
        return jsonify(error="El servicio de análisis no está configurado.", code="SERVICE_UNAVAILABLE"), 503
    supplied = request.headers.get("X-Gateway-Secret", "")
    if not hmac.compare_digest(supplied.encode(), expected.encode()):
        return jsonify(error="Acceso no autorizado.", code="UNAUTHORIZED_DIRECT_IDENTITY"), 403
    try:
        usuario_id = int(request.headers.get("X-User-Id", ""))
        if usuario_id <= 0 or usuario_id > 2147483647:
            raise ValueError()
    except (TypeError, ValueError):
        return jsonify(error="Se requiere una identidad autenticada válida.", code="UNAUTHORIZED_DIRECT_IDENTITY"), 403

    data = request.get_json(silent=True)
    if not isinstance(data, dict) or ("url" in data) == ("text" in data):
        return jsonify(error="Envía exactamente uno de los campos text o url.", code="INVALID_INPUT"), 400
    url = data.get("url")
    text = data.get("text")
    if url is not None:
        if not isinstance(url, str) or not url.strip() or len(url) > 2048:
            return jsonify(error="La URL debe contener entre 1 y 2048 caracteres.", code="INVALID_URL"), 400
        url = url.strip()
    elif not isinstance(text, str) or not 10 <= len(text.strip()) <= 50000:
        return jsonify(error="El texto debe contener entre 10 y 50,000 caracteres.", code="INVALID_TEXT"), 400
    else:
        text = text.strip()
    try:
        # Shared deadline is generated by the authenticated gateway, never the client.
        remaining = min(25.0, float(request.headers.get("X-Request-Deadline", time.time() + 25)) - time.time())
        if not math.isfinite(remaining):
            raise ValueError()
    except (TypeError, ValueError):
        return jsonify(error="Plazo de solicitud inválido.", code="INVALID_INPUT"), 400
    deadline = time.monotonic() + remaining
    def check_deadline():
        if time.monotonic() >= deadline:
            raise TimeoutError("Analysis deadline exceeded")
    try:
        check_deadline()
        modelo_id = get_active_model()
        if modelo_id is None:
            raise ModelUnavailable("No hay un modelo activo configurado.")
        cached = get_cached_analysis(url, text, modelo_id, usuario_id, check_deadline=check_deadline)
        if cached:
            return jsonify(analysis_response(cached)), 200
        snapshot = prepare_model(modelo_id)
        check_deadline()
        extracted = {"Título": "Análisis de texto directo", "Fecha de Publicación": None}
        if url:
            extracted, error = extract_news_data_safe(url)
            check_deadline()
            if error or extracted is None:
                return jsonify(error="No se pudo extraer la noticia de esa URL.", code="EXTRACTION_FAILED"), 400
            text = (extracted.get("Texto Completo") or "").strip()
            if not 10 <= len(text) <= 50000:
                return jsonify(error="El contenido debe contener entre 10 y 50,000 caracteres.", code="INVALID_TEXT"), 400
        resultado, confianza, explicacion = predict_news(text, loaded_model=snapshot)
        check_deadline()
        tema_nombre, tema_id = classify_topic(text)
        keywords = extract_keywords(text)
        saved = save_complete_analysis(
            titulo=extracted.get("Título") or "No disponible", contenido=text, url=url,
            fecha_publicacion=extracted.get("Fecha de Publicación"), fuente_url=url,
            tema_nombre=tema_nombre, tema_id=tema_id, keywords=keywords, modelo_id=snapshot.id,
            resultado=resultado, confianza=confianza, explicacion=explicacion,
            usuario_id=usuario_id, check_deadline=check_deadline)
        return jsonify(analysis_response(saved)), 200
    except ModelUnavailable:
        return jsonify(error="El modelo de análisis no está disponible en este momento.", code="MODEL_UNAVAILABLE"), 503
    except TimeoutError:
        return jsonify(error="El análisis tardó demasiado. Puedes reintentarlo.", code="ANALYSIS_TIMEOUT"), 504
    except Exception:
        logger.exception("Error durante el análisis")
        return jsonify(error="No se pudo completar el análisis. Intenta nuevamente.", code="INTERNAL_ERROR"), 500

@classify_bp.route("/scrape/google", methods=["POST"])
def scrape_google_news():
    """Inicia el scraping de noticias desde Google News y devuelve un CSV con los resultados."""
    try:
        data = request.json or {}
        
        # Obtener parámetros
        rss_url = data.get("rss_url")  # Si es None, usará la URL predeterminada
        limit = data.get("limit", 5)    # Número de noticias a procesar, por defecto 5
        save_to_db = data.get("save_to_db", False)  # Por defecto no guardar en BD
        
        # Iniciar el scraper
        from scrapers.google_news import GoogleNewsScraper
        scraper = GoogleNewsScraper()
        
        # Lista para resultados
        results = []
        
        # Si se debe guardar en BD, usar el método original
        if save_to_db:
            processed_news_ids = scraper.scrape_news(rss_url, limit)
            return jsonify({
                "status": "success",
                "message": f"Se procesaron {len(processed_news_ids)} noticias de Google News correctamente.",
                "processed_ids": processed_news_ids
            }), 200
        else:
            # Si no se guarda en BD, obtenemos los resultados sin guardar
            results = scraper.get_news_without_saving(rss_url, limit)
            
            # Crear un CSV en memoria
            output = io.StringIO()
            fieldnames = [
                "titulo", "url", "fecha_publicacion", "fuente", 
                "contenido", "tema", "clasificacion", "confianza", 
                "palabras_clave"
            ]
            
            writer = csv.DictWriter(output, fieldnames=fieldnames)
            writer.writeheader()
            for item in results:
                writer.writerow({
                    "titulo": item.get("titulo", ""),
                    "url": item.get("url", ""),
                    "fecha_publicacion": item.get("fecha_publicacion", ""),
                    "fuente": item.get("fuente", ""),
                    "contenido": item.get("contenido", "")[:500] + "...",  # Truncar para que no sea muy grande
                    "tema": item.get("tema", ""),
                    "clasificacion": item.get("clasificacion", ""),
                    "confianza": item.get("confianza", ""),
                    "palabras_clave": ", ".join(item.get("palabras_clave", []))
                })
            
            # Crear respuesta CSV
            output.seek(0)
            return Response(
                output.getvalue(),
                mimetype="text/csv",
                headers={"Content-Disposition": "attachment;filename=google_news_results.csv"}
            )
        
    except Exception as e:
        logger.error(f"Error durante el scraping de Google News: {str(e)}")
        return jsonify({
            "status": "error",
            "message": f"Error durante el scraping de Google News: {str(e)}"
        }), 500

@classify_bp.route("/scrape/twitter", methods=["POST"])
def scrape_twitter():
    """Inicia el scraping de tweets y devuelve un CSV con los resultados."""
    try:
        data = request.json or {}
        
        # Obtener parámetros
        query = data.get("query", "noticias salud mexico enfermedad hospital -toro")
        start_date = data.get("start_date")
        end_date = data.get("end_date")
        limit = data.get("limit", 10)
        min_length = data.get("min_length", 50)
        save_to_db = data.get("save_to_db", False)  # Por defecto no guardar en BD
        
        # Iniciar el scraper
        from scrapers.twitter_scraper import TwitterScraper
        scraper = TwitterScraper()
        
        # Si se debe guardar en BD, usar el método original
        if save_to_db:
            processed_news_ids = scraper.scrape_tweets(
                query=query,
                start_date=start_date,
                end_date=end_date,
                limit=limit,
                min_length=min_length
            )
            return jsonify({
                "status": "success",
                "message": f"Se procesaron {len(processed_news_ids)} tweets correctamente.",
                "processed_ids": processed_news_ids
            }), 200
        else:
            # Si no se guarda en BD, obtenemos los resultados sin guardar
            results = scraper.get_tweets_without_saving(
                query=query,
                start_date=start_date,
                end_date=end_date,
                limit=limit,
                min_length=min_length
            )
            
            # Crear un CSV en memoria
            output = io.StringIO()
            fieldnames = [
                "autor", "fecha", "url", "contenido", "tema", 
                "clasificacion", "confianza", "palabras_clave"
            ]
            
            writer = csv.DictWriter(output, fieldnames=fieldnames)
            writer.writeheader()
            for item in results:
                writer.writerow({
                    "autor": item.get("autor", ""),
                    "fecha": item.get("fecha", ""),
                    "url": item.get("url", ""),
                    "contenido": item.get("contenido", ""),
                    "tema": item.get("tema", ""),
                    "clasificacion": item.get("clasificacion", ""),
                    "confianza": item.get("confianza", ""),
                    "palabras_clave": ", ".join(item.get("palabras_clave", []))
                })
            
            # Crear respuesta CSV
            output.seek(0)
            return Response(
                output.getvalue(),
                mimetype="text/csv",
                headers={"Content-Disposition": "attachment;filename=twitter_results.csv"}
            )
        
    except Exception as e:
        logger.error(f"Error durante el scraping de Twitter: {str(e)}")
        return jsonify({
            "status": "error",
            "message": f"Error durante el scraping de Twitter: {str(e)}"
        }), 500
