const assert=require('node:assert/strict');const jwt=require('../../services/auth-service/node_modules/jsonwebtoken');
module.exports=async function({db,secret,instance}){
 let checks=0;const token=id=>jwt.sign({id,rol:'usuario'},secret,{expiresIn:'5m'});
 async function call(path,method='GET',body,status=200,actor=3){const response=await fetch(`http://127.0.0.1:13001/api/auth/profile${path}`,{method,headers:{'Content-Type':'application/json',...(actor?{Authorization:`Bearer ${token(actor)}`}:{})},body:body?JSON.stringify(body):undefined});assert.equal(response.headers.get('x-healthcheck-test-instance'),instance);const json=await response.json();assert.equal(response.status,status,`${path}: ${JSON.stringify(json)}`);checks++;return json.data;}
 await call('/preferences','GET',null,401,null);
 let result=await call('/preferences');assert.equal(result.preferences.recibir_notificaciones,false);assert.equal(result.preferences.id,null);assert.equal(result.delivery_enabled,false);assert.equal((await db.query('SELECT count(*)::int AS n FROM preferencias_usuario')).rows[0].n,0);
 const password='Profile-synthetic-123!';const bcrypt=require('../../services/auth-service/node_modules/bcryptjs');await db.query('UPDATE usuarios SET telefono=$1,contrasena=$2 WHERE id=3',['5550000000',await bcrypt.hash(password,10)]);
 const login=await fetch('http://127.0.0.1:13001/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'normal@example.invalid',contrasena:password})});assert.equal(login.status,200);const session=(await login.json()).data;assert.equal(session.user.telefono,'5550000000','Login must supply complete editable profile');assert(session.user.fecha_registro);checks++;
 const user=await call('','PUT',{nombre:'Profile synthetic',telefono:session.user.telefono,imagen_url:'https://example.invalid/avatar.png',rol:'admin'});assert.equal(user.user.telefono,'5550000000');assert.equal(user.user.imagen_url,'https://example.invalid/avatar.png');assert.equal(user.user.rol,'usuario');assert.equal((await call('')).user.imagen_url,user.user.imagen_url);
 await call('','PUT',{imagen_url:'javascript:alert(1)'},400);await call('','PUT',{imagen_url:''});assert.equal((await call('')).user.imagen_url,null);
 await call('/preferences','PUT',{recibir_notificaciones:'yes',frecuencia_notificaciones:'diaria',tipo_notificacion:'email'},400);
 const prefs={recibir_notificaciones:true,frecuencia_notificaciones:'semanal',tipo_notificacion:'email'};await Promise.all([call('/preferences','PUT',prefs),call('/preferences','PUT',prefs)]);assert.equal((await db.query('SELECT count(*)::int AS n FROM preferencias_usuario WHERE usuario_id=3')).rows[0].n,1);
 await call('','PUT',{telefono:''});await call('/preferences','PUT',{...prefs,tipo_notificacion:'sms'},400);
 const topic=(await db.query("INSERT INTO temas(nombre,activo) VALUES('Profile active topic',true) RETURNING id")).rows[0].id;const inactive=(await db.query("INSERT INTO temas(nombre,activo) VALUES('Profile inactive topic',false) RETURNING id")).rows[0].id;
 assert((await call('/topics')).some(t=>t.id===topic));assert(!(await call('/topics')).some(t=>t.id===inactive));
 await call('/topics','POST',{tema_id:inactive},404);result=await call('/topics','POST',{tema_id:topic,usuario_id:1});assert(result.topics.some(t=>t.tema_id===topic));await call('/topics','POST',{tema_id:topic});assert.equal((await db.query('SELECT count(*)::int AS n FROM preferencias_usuario_temas WHERE usuario_id=3 AND tema_id=$1',[topic])).rows[0].n,1);
 assert(!(await call('/preferences','GET',null,200,1)).topics.some(t=>t.tema_id===topic));await call(`/topics/${topic}`,'DELETE');assert(!(await call('/preferences')).topics.some(t=>t.tema_id===topic));
 const records=(await db.query("INSERT INTO notificaciones(usuario_id,titulo,mensaje,tipo) VALUES(3,'Own','Synthetic','email'),(1,'Other','Synthetic','email') RETURNING id,usuario_id")).rows;const own=records.find(n=>n.usuario_id===3).id,other=records.find(n=>n.usuario_id===1).id;
 result=await call('/notifications');assert.equal(result.total,1);assert.equal(result.items[0].id,own);await call(`/notifications/${other}`,'DELETE',null,404);await call(`/notifications/${own}`,'DELETE');assert.equal((await call('/notifications')).total,0);assert.equal((await db.query('SELECT count(*)::int AS n FROM notificaciones WHERE id=$1',[other])).rows[0].n,1);
 await call('/notifications?limit=999','GET',null,400);
 console.log(`PASS: ${checks} profile HTTP checks; owner isolation, URL persistence, read-only defaults, preference concurrency and topics verified. No delivery invoked.`);
};
